// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameCustomer = "Customer"

// Customer mapped from table <Customer>
type Customer struct {
	ID        int64   `gorm:"column:Id;type:int;primaryKey" json:"Id"`
	FirstName string  `gorm:"column:FirstName;type:nvarchar;not null" json:"FirstName"`
	LastName  string  `gorm:"column:LastName;type:nvarchar;not null" json:"LastName"`
	City      *string `gorm:"column:City;type:nvarchar" json:"City"`
	Country   *string `gorm:"column:Country;type:nvarchar" json:"Country"`
	Phone     *string `gorm:"column:Phone;type:nvarchar" json:"Phone"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
