// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameMasterType = "Master_Type"

// MasterType mapped from table <Master_Type>
type MasterType struct {
	MasterTypeID  *[]uint8 `gorm:"column:Master_Type_Id;type:uniqueidentifier;primaryKey" json:"Master_Type_Id"`
	MasterChartID []uint8  `gorm:"column:Master_Chart_Id;type:uniqueidentifier;not null" json:"Master_Chart_Id"`
	Lable         string   `gorm:"column:Lable;type:nvarchar;not null" json:"Lable"`
}

// TableName MasterType's table name
func (*MasterType) TableName() string {
	return TableNameMasterType
}
