// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameMasterChart = "Master_Chart"

// MasterChart mapped from table <Master_Chart>
type MasterChart struct {
	MsChartID *[]uint8 `gorm:"column:Ms_Chart_Id;type:uniqueidentifier;primaryKey" json:"Ms_Chart_Id"`
	Type      string   `gorm:"column:Type;type:nvarchar;not null" json:"Type"`
	IsActive  *bool    `gorm:"column:IsActive;type:bit;not null;default:1" json:"IsActive"`
	Seq       *int64   `gorm:"column:Seq;type:int" json:"Seq"`
}

// TableName MasterChart's table name
func (*MasterChart) TableName() string {
	return TableNameMasterChart
}
