// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameOrderItem = "OrderItem"

// OrderItem mapped from table <OrderItem>
type OrderItem struct {
	ID        int64    `gorm:"column:Id;type:int;primaryKey" json:"Id"`
	OrderID   int64    `gorm:"column:OrderId;type:int;not null" json:"OrderId"`
	ProductID int64    `gorm:"column:ProductId;type:int;not null" json:"ProductId"`
	UnitPrice *[]uint8 `gorm:"column:UnitPrice;type:decimal;not null;default:0" json:"UnitPrice"`
	Quantity  *int64   `gorm:"column:Quantity;type:int;not null;default:1" json:"Quantity"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
