// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

import (
	"time"
)

const TableNameOrder = "Order"

// Order mapped from table <Order>
type Order struct {
	ID          int64      `gorm:"column:Id;type:int;primaryKey" json:"Id"`
	OrderDate   *time.Time `gorm:"column:OrderDate;type:datetime;not null;default:getdate()" json:"OrderDate"`
	OrderNumber *string    `gorm:"column:OrderNumber;type:nvarchar" json:"OrderNumber"`
	CustomerID  int64      `gorm:"column:CustomerId;type:int;not null" json:"CustomerId"`
	TotalAmount *[]uint8   `gorm:"column:TotalAmount;type:decimal;default:0" json:"TotalAmount"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
