// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameProduct = "Product"

// Product mapped from table <Product>
type Product struct {
	ID             int64    `gorm:"column:Id;type:int;primaryKey" json:"Id"`
	ProductName    string   `gorm:"column:ProductName;type:nvarchar;not null" json:"ProductName"`
	SupplierID     int64    `gorm:"column:SupplierId;type:int;not null" json:"SupplierId"`
	UnitPrice      *[]uint8 `gorm:"column:UnitPrice;type:decimal;default:0" json:"UnitPrice"`
	Package        *string  `gorm:"column:Package;type:nvarchar" json:"Package"`
	IsDiscontinued *bool    `gorm:"column:IsDiscontinued;type:bit;not null;default:0" json:"IsDiscontinued"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
