// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameProfileChart = "Profile_Chart"

// ProfileChart mapped from table <Profile_Chart>
type ProfileChart struct {
	ConfigChartID *[]uint8 `gorm:"column:Config_Chart_Id;type:uniqueidentifier;primaryKey" json:"Config_Chart_Id"`
	DataKeys      string   `gorm:"column:DataKeys;type:nvarchar;not null" json:"DataKeys"`
	Type          *string  `gorm:"column:Type;type:nvarchar" json:"Type"`
	Oprions       *string  `gorm:"column:Oprions;type:nvarchar" json:"Oprions"`
}

// TableName ProfileChart's table name
func (*ProfileChart) TableName() string {
	return TableNameProfileChart
}
