// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package schema

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID   *[]uint8 `gorm:"column:Id;type:uniqueidentifier;primaryKey" json:"Id"`
	Name *int64   `gorm:"column:Name;type:int" json:"Name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
